# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *
from PyQt5.QtCore import QCoreApplication, QUrl

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(758, 392)
        Form.setMinimumSize(QtCore.QSize(758, 392))
        Form.setMaximumSize(QtCore.QSize(758, 392))
        Form.setStyleSheet("background-color: rgb(77, 77, 77);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 739, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 12pt \"Open Sans ExtraBold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 101, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 12pt \"Open Sans ExtraBold\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 101, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 12pt \"Open Sans ExtraBold\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 101, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 81 12pt \"Open Sans ExtraBold\";")
        self.label_5.setObjectName("label_5")
        self.title_weather = QtWidgets.QLabel(Form)
        self.title_weather.setGeometry(QtCore.QRect(290, 100, 191, 161))
        font = QtGui.QFont()
        font.setFamily("HACKED")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_weather.setFont(font)
        self.title_weather.setStyleSheet("font: 35pt \"HACKED\";\n"
"color: rgb(255, 255, 255);")
        self.title_weather.setAlignment(QtCore.Qt.AlignCenter)
        self.title_weather.setObjectName("title_weather")
        self.first_button = QtWidgets.QPushButton(Form)
        self.first_button.setGeometry(QtCore.QRect(40, 280, 121, 91))
        self.first_button.setStyleSheet("font: 30pt \"HACKED\";\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 5px;\n"
"border-radius:10px;\n"
"border-color: rgb(85, 255, 255);\n"
"")
        self.first_button.setFlat(True)
        self.first_button.setObjectName("first_button")
        self.second_button = QtWidgets.QPushButton(Form)
        self.second_button.setGeometry(QtCore.QRect(180, 280, 121, 91))
        self.second_button.setStyleSheet("font: 30pt \"HACKED\";\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 5px;\n"
"border-radius:10px;\n"
"border-color: rgb(85, 255, 255);\n"
"")
        self.second_button.setFlat(True)
        self.second_button.setObjectName("second_button")
        self.third_button = QtWidgets.QPushButton(Form)
        self.third_button.setGeometry(QtCore.QRect(320, 280, 121, 91))
        self.third_button.setStyleSheet("font: 30pt \"HACKED\";\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 5px;\n"
"border-radius:10px;\n"
"border-color: rgb(85, 255, 255);\n"
"")
        self.third_button.setFlat(True)
        self.third_button.setObjectName("third_button")
        self.fourth_button = QtWidgets.QPushButton(Form)
        self.fourth_button.setGeometry(QtCore.QRect(460, 280, 121, 91))
        self.fourth_button.setStyleSheet("font: 30pt \"HACKED\";\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 5px;\n"
"border-radius:10px;\n"
"border-color: rgb(85, 255, 255);\n"
"")
        self.fourth_button.setFlat(True)
        self.fourth_button.setObjectName("fourth_button")
        self.fifth_button = QtWidgets.QPushButton(Form)
        self.fifth_button.setGeometry(QtCore.QRect(600, 280, 121, 91))
        self.fifth_button.setStyleSheet("font: 30pt \"HACKED\";\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width: 5px;\n"
"border-radius:10px;\n"
"border-color: rgb(85, 255, 255);\n"
"")
        self.fifth_button.setFlat(True)
        self.fifth_button.setObjectName("fifth_button")
        self.current_weather_label = QtWidgets.QPushButton(Form)
        self.current_weather_label.setGeometry(QtCore.QRect(0, 52, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.current_weather_label.setFont(font)
        self.current_weather_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:5px;\n"
"border-radius:10px;\n"
"border-color: rgb(255, 255, 255);")
        self.current_weather_label.setObjectName("current_weather_label")
        self.time_label = QtWidgets.QLabel(Form)
        self.time_label.setGeometry(QtCore.QRect(60, 90, 151, 31))
        self.time_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Segoe UI\";")
        self.time_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.time_label.setObjectName("time_label")
        self.quality_label = QtWidgets.QLabel(Form)
        self.quality_label.setGeometry(QtCore.QRect(110, 130, 101, 31))
        self.quality_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Segoe UI\";")
        self.quality_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.quality_label.setObjectName("quality_label")
        self.wind_label = QtWidgets.QLabel(Form)
        self.wind_label.setGeometry(QtCore.QRect(60, 170, 151, 31))
        self.wind_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Segoe UI\";")
        self.wind_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wind_label.setObjectName("wind_label")
        self.gusts_label = QtWidgets.QLabel(Form)
        self.gusts_label.setGeometry(QtCore.QRect(120, 210, 91, 31))
        self.gusts_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Segoe UI\";")
        self.gusts_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gusts_label.setObjectName("gusts_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "My Weather App"))
        self.label_2.setText(_translate("Form", "Time:"))
        self.label_3.setText(_translate("Form", "Air Quality:"))
        self.label_4.setText(_translate("Form", "Wind Gusts:"))
        self.label_5.setText(_translate("Form", "Wind:"))
        self.title_weather.setText(_translate("Form", "24"))
        self.first_button.setText(_translate("Form", "34"))
        self.second_button.setText(_translate("Form", "37"))
        self.third_button.setText(_translate("Form", "40"))
        self.fourth_button.setText(_translate("Form", "41"))
        self.fifth_button.setText(_translate("Form", "38"))
        self.current_weather_label.setText(_translate("Form", "Current Weather..."))
        self.time_label.setText(_translate("Form", "12PM"))
        self.quality_label.setText(_translate("Form", "12PM"))
        self.wind_label.setText(_translate("Form", "12PM"))
        self.gusts_label.setText(_translate("Form", "12PM"))
